### ISSUE TITLE
Add support for Cross-Origin Resource Sharing (CORS).

### ISSUE THREAD

**Issue by nicomiguelino** [nicomiguelino/twitter-django-api#16]
# Tasks

- [x] Install the latest version of `django-cors-headers` (`~=3.10.0`).
- [x] Modfiy `settings.py` &mdash; add apps and middleware relevant to CORS.
- [x] Modify `settings.py` &mdash; allow all origins (for the meantime). We make the settings more strict later on.
