### ISSUE TITLE
Create a new model for user accounts.

### ISSUE THREAD

**Issue by nicomiguelino** [nicomiguelino/twitter-django-api#5]
# Tasks

- [x] Create a new app called `users`. Don't forget to include it in the `INSTALLED_APPS` inside `twittter_django_api/settings.py`.
- [x] Create a model for the `User`. It must inherit from the `AbstractUser` model class. Don't forget to modify `twitter_django_api/settings.py`.
- [x] Write unit tests.
- [x] Modify `devtools/management/commands/seed.py` so that it will include the creation of user accounts (whether it's a superuser or not).
- [x] Modify `users/admin.py` so that the admin can manage user accounts.
- [x] Remove the unnecessary files created by running the `startapp` management command.
- [x] Modify `README.md` so that it will have instructions on how to properly run migrationsif you've used a custom user model later on (instead of not doing it when you create the project).
- [x] Run formatters and linters on your code before pushing your changes.
