### ISSUE TITLE
Establish a one-to-many relationship between user account and tweets.

### ISSUE THREAD

**Issue by nicomiguelino** [nicomiguelino/twitter-django-api#6]
# Tasks

- [x] Add a new field under the `Tweet` model (from `/tweets/models.py`).
- [x] Write unit tests for `tweets/models.py`.
- [x] Write unit tests for `users/models.py`.
- [x] Modify `tweets/admin.py`.
- [x] Modify `users/admin.py` (if possible).
- [x] Modify `graphql_api/schema.py`.
- [x] Modify `devtools/management/commands/seed.py`.
- [x] Apply linting and formatting changes.
