### ISSUE TITLE
Modify the GraphQL schema so that it will include support for JSON Web Tokens (JWT).

### ISSUE THREAD

**Issue by nicomiguelino** [nicomiguelino/twitter-django-api#7]
# Tasks

- [x] Install the latest version of `django-graphql-jwt` (`~= 0.3.4`).
- [x] Perform first-time setups as seen in the [repo page of `django-graphql-jwt`](https://github.com/flavors/django-graphql-jwt#installation).
- [x] [Modify the schema of your GraphQL API](https://github.com/flavors/django-graphql-jwt#schema) so that it will include mutations for authentication.
- [x] Enable HTTP-only cookie for JWT.
- [ ] Customize the error message displayed when accessing queries or mutations that require login. Make sure to include the status code.
